version: '3.8'

services:
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ../apps/python-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../apps/python-backend/app:/app
    environment:
      - ENVIRONMENT=development 